version: '3'

services:
  mysql:
    image: mysql:5.7.28
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_pass
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql_pass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data: